<?php

/**
 * @file
 * This will turn the standard HTML code editor into an Ace HTML code editor
 */

/*
 * IMPORTANT NOTE:
 * When installing this module (ace), always click on
 * "check manually" inside the yellow "No update information available" message
 *
 * Also go to admin > config > performance and clear the cache.
 *
 */

/**
 * Implements hook_wysiwyg_plugin().
 */
function ace_wysiwyg_plugin($editor, $version) {

	// To get this fully working, the tinymce-ace plugin must be added
	// to the tiny mce plugins directory
	// So far, it only supports v3.

	if ($editor === 'tinymce'){

		return array(
			'ace' => array(
				'path' => wysiwyg_get_path('tinymce') . '/jscripts/tiny_mce/plugins/ace',
				'filename' => 'editor_plugin.js',
				'buttons' => array('ace' => t('Ace Code Editor (Must have "Source Code" also selected)')),
				'url' => 'http://www.websiteconnect.com.au/',
				'internal' => false,
				'load' => true,
			),
		);
	}

	return array();

}